steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/image-converter-backend', 'backend'] # backend ディレクトリをビルドコンテキストとして指定
  dir: '.' # リポジトリのルートで実行

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'photo-converter' # Cloud Run サービス名 (前回設定したもの)
  - '--image'
  - 'gcr.io/${PROJECT_ID}/photo-converter'
  - '--region'
  - 'asia-northeast1' # デプロイするリージョン (前回設定したもの)
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated' # 未認証アクセスを許可
  - '--project=${PROJECT_ID}'