steps:
# バックエンドのビルドとデプロイ
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/image-converter-backend', 'backend']
  dir: '.'

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'photo-converter'
  - '--image'
  - 'gcr.io/${PROJECT_ID}/image-converter-backend'
  - '--region'
  - 'asia-northeast1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--project=${PROJECT_ID}'

# フロントエンドのビルドとデプロイ
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: 'frontend'

- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
  dir: 'frontend'

# ★★★ デバッグ用ステップ ★★★
# buildで生成されたdistディレクトリの中身を確認する
- name: 'ubuntu'
  args: ['ls', '-R', 'frontend/dist']
  dir: '.'

# フロントエンドのファイルをCloud Storageにデプロイ
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gsutil
  args:
  - '-m'
  - 'rsync'
  - '-r'
  - 'frontend/dist'
  - 'gs://photo-converter-frontend-matsuishi'

  options:
  logging: CLOUD_LOGGING_ONLY