steps:
# バックエンドのビルドとプッシュ
- name: 'gcr.io/cloud-builders/docker'
  id: 'バックエンドイメージのビルド'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/image-converter-backend', 'backend']
  dir: '.'
- name: 'gcr.io/cloud-builders/docker'
  id: 'バックエンドイメージのプッシュ'
  args: ['push', 'gcr.io/${PROJECT_ID}/image-converter-backend']

# バックエンドをCloud Runにデプロイ
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'バックエンドのデプロイ'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'photo-converter'
  - '--image'
  - 'gcr.io/${PROJECT_ID}/image-converter-backend'
  - '--region'
  - 'asia-northeast1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--project=${PROJECT_ID}'

# フロントエンドのビルド
- name: 'gcr.io/cloud-builders/npm'
  id: 'フロントエンドの依存関係インストール'
  args: ['install']
  dir: 'frontend'
- name: 'gcr.io/cloud-builders/npm'
  id: 'フロントエンドのビルド'
  args: ['run', 'build']
  dir: 'frontend'
  env:
  - 'VITE_API_URL=https://photo-converter-backend-a6k4n5l23a-an.a.run.app'

# ★★★ ここに新しいステップを追加 ★★★
# 古いフロントエンドのファイルをバケットから削除する
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: '古いフロントエンドファイルを削除'
  entrypoint: 'gsutil'
  args: ['-m', 'rm', '-f', '-r', 'gs://photo-converter-frontend-matsuishi/**']

# フロントエンドのファイルをCloud Storageにデプロイ
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'フロントエンドのデプロイ'
  entrypoint: gsutil
  args:
  - '-m'
  - 'rsync'
  - '-r'
  - 'frontend/dist'
  - 'gs://photo-converter-frontend-matsuishi'

# ログ設定
options:
  logging: CLOUD_LOGGING_ONLY