steps:
# バックエンドのDockerイメージをビルドする
- name: 'gcr.io/cloud-builders/docker'
  id: 'バックエンドイメージのビルド'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/image-converter-backend', 'backend']
  dir: '.'

# ★★★ ここに新しいステップを追加 ★★★
# ビルドしたイメージをGoogle Container Registryにプッシュする
- name: 'gcr.io/cloud-builders/docker'
  id: 'バックエンドイメージのプッシュ'
  args: ['push', 'gcr.io/${PROJECT_ID}/image-converter-backend']

# バックエンドをCloud Runにデプロイする
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'バックエンドのデプロイ'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'photo-converter'
  - '--image'
  - 'gcr.io/${PROJECT_ID}/image-converter-backend'
  - '--region'
  - 'asia-northeast1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--project=${PROJECT_ID}'

# フロントエンドの依存関係をインストール
- name: 'gcr.io/cloud-builders/npm'
  id: 'フロントエンドの依存関係インストール'
  args: ['install']
  dir: 'frontend'

# フロントエンドをビルドする
- name: 'gcr.io/cloud-builders/npm'
  id: 'フロントエンドのビルド'
  args: ['run', 'build']
  dir: 'frontend'

# フロントエンドのファイルをCloud Storageにデプロイする
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'フロントエンドのデプロイ'
  entrypoint: gsutil
  args:
  - '-m'
  - 'rsync'
  - '-r'
  - 'frontend/dist'
  - 'gs://photo-converter-frontend-matsuishi'

# ログ設定
options:
  logging: CLOUD_LOGGING_ONLY